// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa12DKRqqFDgiOE_HRpWIr43HwGqY5qAY',
    appId: '1:648703402718:android:95ee0bd9010d252448984f',
    messagingSenderId: '648703402718',
    projectId: 'uniquiz-fdb94',
    storageBucket: 'uniquiz-fdb94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_z-9mk--eNP88Pzmcvvb5gyTFPml9w4',
    appId: '1:648703402718:ios:6cea697b05cd8aa748984f',
    messagingSenderId: '648703402718',
    projectId: 'uniquiz-fdb94',
    storageBucket: 'uniquiz-fdb94.appspot.com',
    androidClientId: '648703402718-1n0f4qniemto11a2bsfvb5rscprj2h5v.apps.googleusercontent.com',
    iosClientId: '648703402718-v722nt5qpameidpsqphsun66sl3rg1ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniquiz',
  );
}
